run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  show-stats: true

issues:
  exclude-dirs:
    - vendor
    - bin
    - examples
    - PRPs
  exclude-files:
    - ".*_generated.go$"
  uniq-by-line: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - copyloopvar
    - revive
  disable:
    - gosimple  # Too pedantic about style choices
    - prealloc  # Too pedantic about slice preallocation
    - whitespace  # Too pedantic about formatting
  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - nilfunc
      - printf
      - structtag
      - tests
      - unreachable
      - unsafeptr

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/derekxwang/tcs

  misspell:
    locale: US

  unparam:
    check-exported: false
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # Skip vendor and external directories
    - path: vendor/
      linters:
        - unused
    - path: examples/
      linters:
        - unused
    
    # Skip Go module cache files
    - path: ".*/go/pkg/mod/.*"
      linters:
        - typecheck
        - unused
        - gosimple
        - staticcheck

  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10